# Generated by Django 4.2.30 on 2026-05-07 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotenciaCreacionLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=128, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('anio', models.PositiveSmallIntegerField()),
                ('genero', models.CharField(choices=[('ficcion', 'Ficción'), ('no_ficcion', 'No ficción'), ('poesia', 'Poesía'), ('ensayo', 'Ensayo'), ('infantil', 'Infantil'), ('otro', 'Otro')], max_length=32)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-actualizado_en', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='libro',
            constraint=models.CheckConstraint(check=models.Q(('anio__gte', 1000), ('anio__lte', 2100)), name='libro_anio_rango'),
        ),
        migrations.AddField(
            model_name='idempotenciacreacionlibro',
            name='libro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idempotencia_origen', to='libros.libro'),
        ),
    ]
